### ISSUE TITLE
The hair color/hairstyle list was better than the ID input.

### ISSUE THREAD

**Issue by Mell825** [RedShyGuy/Vapecord-ACNL-Plugin#11]
Please add back the list of hairstyles/colors bc the ID input is stoopid

**Comment by Mell825** [comment]
How are all us poor unfortunate souls that dont know hair IDs going to get rid of our "yuck" hair

**Comment by Mell825** [comment]
**:D**

**Comment by RedShyGuy** [comment]
Use the ID List Website I specifically made for the plugins input!
