### ISSUE TITLE
Loading plugin ...

### ISSUE THREAD

**Issue by ninzab0y** [RedShyGuy/Vapecord-ACNL-Plugin#121]
I have a problem because it just says
loading plugin.. What can i do?

**Comment by Banzar44** [comment]
I am having this same issue. When I first load the game (ACNL:WA), the top screen flashes blue as expected, then in the top-left of the top screen, the message 'Loading Plugin' with a loading icon persists until game exit. 
Game version:  Welcome Amiibo
Vapecord version:  [v1.9.6][QUICKFIX] (the latest as of this post)
![HNI_0071](https://user-images.githubusercontent.com/15897953/228141380-7a0e1a6c-6694-4ebd-8886-6990686b0f96.JPG)

**Comment by RedShyGuy** [comment]
Your game most likely is not the newest version, make sure to update it

**Comment by FoofooTheGuy** [comment]
I fixed this in [34dc356](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/commit/34dc3565a88d445205c8aad94a43016957b30dc6)
