### ISSUE TITLE
Text on the right side of the screen

### ISSUE THREAD

**Issue by moloukouveyi** [RedShyGuy/Vapecord-ACNL-Plugin#124]
I don't know how it happened, but text of all the loading elements on the screen on the right side.
How can I hide it? I tried to delete and reinstall Vapecord, but it's still there…
![20230404_230117](https://user-images.githubusercontent.com/129903037/229922020-d787287c-9977-4a30-9d0b-709b55e8b505.jpg)

**Comment by TwystedXYZ** [comment]
vapecord menu -> tools (bottom screen) -> miscellaneous -> display loaded game files

**Comment by moloukouveyi** [comment]
Thank you very much!
