### ISSUE TITLE
Game crashes after loading plugin

### ISSUE THREAD

**Issue by Neocatt** [RedShyGuy/Vapecord-ACNL-Plugin#127]
Exception type:data abort

**Comment by Neocatt** [comment]
![image](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/assets/133054552/944fbb9c-0b3b-49ee-85b1-c68dae49ba13)

**Comment by FoofooTheGuy** [comment]
What region is your 3DS?

**Comment by RedShyGuy** [comment]
Closing this due to no response
