### ISSUE TITLE
[FEATURE REQUEST] Chat filter

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#13]
Hello. I would like to request this:

-------------------------------------------
Input/deletion of words to filter in chat,
Storage of words in file,
It blocks chat filter bypasses, (using german letters for to bypass and say bad things in chat)

-------------------------------------------

Thanks. Please add this, I think it would make a good cheat. :P

**Comment by RedShyGuy** [comment]
Hm it would probably only work for messages you send, not for others because we get the data of sent messages from others only when they sent it

**Comment by SirEnder125** [comment]
Oh, well if you find a way in the future, please implement it into the plugin! :D

**Comment by SirEnder125** [comment]
Maybe something like Non-Hacker cheat; Instead of doing an animation, placing an item, etc. When the text is found in chat it is
blocked instead? Maybe this is a dumb suggestion, but I don't know.
