### ISSUE TITLE
URGENT ISSUE, CONTACT IMMEDIATELY

### ISSUE THREAD

**Issue by TwystedXYZ** [RedShyGuy/Vapecord-ACNL-Plugin#130]
I've found a player online that has utilized some form of cheat in order to break through Vapecord's Anti-Animation. Please contact via Discord ASAP: 
twystedxyz

**Comment by RedShyGuy** [comment]
The project is discontinued, I am not working on it anymore

**Comment by TwystedXYZ** [comment]
...Oh.

**Comment by FoofooTheGuy** [comment]
This was an issue unrelated to the Anti-Animation
