### ISSUE TITLE
Luma 13

### ISSUE THREAD

**Issue by StikoNiko** [RedShyGuy/Vapecord-ACNL-Plugin#133]
Hi,
First, Your Plugin is great. I Love this.

The new Luma hast Pluginsupport.
The Last Luma hast a extra Version for Plugins 

The new ist a one in all package.

But Your Plugin does Not Work with the new Luma 13+.
I Hope for a Solution with the coming Luma Updates.

You have make ACNL great with this Plugin.
Thanks.

**Comment by CodyMKW** [comment]
I updated to Luma 13 and Vapecord works just fine for me was using it last night with no issues
