### ISSUE TITLE
[Bug] Appearance modifier (hair changer etc.) doesn't work!

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#14]
The appearance modifier only works if you follow these steps:
-----------------------------------------
1. Set the appearance settings
2. switch to animation mode and do animation B9
-----------------------------------------

The cheat does animation B9 but sets the ids to bold hair, default eye color, etc. (It should use the id's entered by user)

Please fix this.

Thanks.

**Comment by RedShyGuy** [comment]
The appearance modifier inside Player Codes has nothing to do with the one inside Animation Codes, both work just fine.

**Comment by SirEnder125** [comment]
No, no, you don't understand, I mean the player code one works, but, at least in ACNL USA, you have to use animation mode instead of appearance mode IN the animation modifier and use animation B9,
In other words, you have to do it manually instead of appearance mode doing it right.

**Comment by RedShyGuy** [comment]
Hm you need to set the Appearance too by pressing A + DPadLeft and select all 3 appearance things (Hair Color, Hair Style and Eye Color)

**Comment by SirEnder125** [comment]
Yes, I set the colors and press the hotkeys to execute the appearance change, but I get bald hair. But, for some reason,
using animation mode and entering B9 after setting the IDS works, but the appearance changer doesn't.

--------------------------------------
Thanks.

**Comment by RedShyGuy** [comment]
Hm that actually doesnt make sense😅, both of them work exactly the same, do you maybe have Animation Speed active? Maybe that interfers with something

**Comment by SirEnder125** [comment]
I'll try the cheat again in a bit.
---------------------------------
(By the way I'm still getting random errors...)

**Comment by RedShyGuy** [comment]
There are no random crashes, something invalid must happen for it to crash. But if you cant find out which cheat does the crash i cant help sorry😕

**Comment by SirEnder125** [comment]
Well, It happens when I'm not even playing, when I go away for a second, etc. ...
I can't figure out why.

**Comment by RedShyGuy** [comment]
Try switching off codes, and see if it still happens until it doesnt anymore, then switch on codes again and see which one it is

**Comment by SirEnder125** [comment]
I'll try it when I have my 2DS next week, I don't use it on weekdays. I'll see what happens then.

**Comment by SirEnder125** [comment]
So, I can't seem to make it work.
Do you understand the bug that I reported?

If you press A+B when on appearance mode of animation changer, you get bald hair. At least, I do...
:/

**Comment by RedShyGuy** [comment]
Oooh now I see the problem! I will fix that problem as fast as possible. Thanks for reporting it!🙂 (The thing was I couldn't reproduce the issue cause i had Game Speed active which makes it work again😅)
