### ISSUE TITLE
Mannequin IDs don’t work :( 

### ISSUE THREAD

**Issue by Sigilla** [RedShyGuy/Vapecord-ACNL-Plugin#142]
Hello!! I wanted to give a friend of mine some Gracie mannequins since she’s been looking for some but when I tried putting in the codes it kept saying invalid ID even though it were the right ones :( 

Is there a reason behind it, perhaps I missed out on an update or the codes are outdated? 

Thank you, have a great day !

**Comment by FoofooTheGuy** [comment]
Mannequin IDs are blocked on purpose because the game will crash if more than one is used. Notice how each mannequin has a unique ID, they work very weirdly.
