### ISSUE TITLE
Please update vapecord to work in new updated Luma

### ISSUE THREAD

**Issue by NaomiRedPanda** [RedShyGuy/Vapecord-ACNL-Plugin#144]
This version of vapecord replaces my new updated Luma with 10.3 3gx luma. If you can please update it

**Comment by FoofooTheGuy** [comment]
update luma manually https://github.com/LumaTeam/Luma3DS/releases/latest

**Comment by FoofooTheGuy** [comment]
The next release will no longer come with a boot.firm since the plugin loader is in the regular luma now
