### ISSUE TITLE
Outdated plugin file Check for an updated plugin. Error code: 6x10E87402 : tried downloading vape cord acnl plugin and use the plugin and this error code happened 

### ISSUE THREAD

**Issue by madisonmadds** [RedShyGuy/Vapecord-ACNL-Plugin#145]
Hi, I downloaded the newest version of acnl vapecord plugin. When I open acnl it gives me this error code when I try to use the plugin. The error code is , “ Outdated plugin file
Check for an updated plugin.
Error code: 6x10E87402.” What do I do? Help please!

**Comment by FoofooTheGuy** [comment]
Make sure it is the only plugin in the directory that the game is trying to load a plugin from. Did you have something there before installing it?
Also make sure luma is up to date.

**Comment by RedShyGuy** [comment]
Closing this due to no answer by the issue creator
