### ISSUE TITLE
Unable to dump a Dream Town

### ISSUE THREAD

**Issue by Rodostlyn69** [RedShyGuy/Vapecord-ACNL-Plugin#148]
Hello. I wondered if its possible to dump a dream town with Vapecord, because for me didn't work. Did I done something wrong? Anyways, every time it seems it is done, the game loads the outside of the city and it crashes, and, when I speak to Isabelle with the dream town cloned, the game crashes. The strange thing is that I can stay in public structures, like the station, normally, but not in the outside of the city.

**Comment by FoofooTheGuy** [comment]
What code are you using to do this?

**Comment by Rodostlyn69** [comment]
> What code are you using to do this?

I'm using save dumper, before going into the dream town, and save restorer after i'm in the dream town.

**Comment by Rodostlyn69** [comment]
> Save dumper is, believe it or not, for dumping your save (GardenPlus) so it should indeed not be able to dump the dream town that you are visiting.
> However, it really shouldn’t crash no matter what you do, so I guess that code needs some work.

So, how can I dump the dream town to have it in my save file?

**Comment by FoofooTheGuy** [comment]
Oh, interesting. I must have misinterpreted the behavior of the code, sorry!
I shall test it out later

**Comment by FoofooTheGuy** [comment]
Well, it works fine when I used it on USA ACNLWA, what region and revision of ACNL do you have?

**Comment by Rodostlyn69** [comment]
> Well, it works fine when I used it on USA ACNLWA, what region and revision of ACNL do you have? Or better yet, send a picture of the crash screen.

I can't send a picture of the crash screen right now, but i can tell you what version of the game i'm using.

My game cartridge is Animal Crossing: New Leaf standard, without the Welcome Amiibo Update. The Welcome Amiibo Update was installed before doing the dump of the dream town.

**Comment by FoofooTheGuy** [comment]
I've just tested it on EUR acnl + update data and it works fine for me too. But it might be because I'm using a build of the latest commit and not 1.9.6
try this build and see if it makes anything better
[Vapecord-ACNL-Plugin-master.zip](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/files/13640310/Vapecord-ACNL-Plugin-master.zip)

**Comment by Rodostlyn69** [comment]
> I've just tested it on EUR acnl + update data and it works fine for me too. But it might be because I'm using a build of the latest commit and not 1.9.6
> try this build and see if it makes anything better
> [Vapecord-ACNL-Plugin-master.zip](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/files/13640310/Vapecord-ACNL-Plugin-master.zip)
> 

It still crashes, even with your build

**Comment by Rodostlyn69** [comment]
> Well, it works fine when I used it on USA ACNLWA, what region and revision of ACNL do you have? Or better yet, send a picture of the crash screen.

I will send the crash dump Vapecord generated, if that can help you!


[Crash_Dump [2024-01-05_05-54PM].txt](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/files/13850511/Crash_Dump.2024-01-05_05-54PM.txt)

**Comment by FoofooTheGuy** [comment]
For future reference, this was not an issue with the plugin, but a specific case of some weird corruption with the town where any part of the save file where nothing was written to had partial text from other stuff in it instead of just being 00. It was fixed by putting 00 in every place that had the corruption.
