### ISSUE TITLE
My plugin interface language is garbled

### ISSUE THREAD

**Issue by siemanzzz** [RedShyGuy/Vapecord-ACNL-Plugin#149]
My plugin interface language is garbled and I can't read any of the words on it
![9252D6F2E9E3C7793B443863DF6EF43D](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/assets/154597783/995b1146-5dc0-467c-ab0c-088626c3d5d5)

**Comment by FoofooTheGuy** [comment]
CTRPF does not support custom fonts. It may be fixable if font loading is made more similar to how the home menu does it or something, who knows…

**Comment by siemanzzz** [comment]
> CTRPF 不支持自定义字体。如果字体加载与主菜单的加载方式更加相似，那么它可能是可以修复的，谁知道呢……

idk maybe it's because my 3ds language is Chinese

**Comment by FoofooTheGuy** [comment]
Yes that is the other case that will cause this. a while back, they fixed it for the Chinese font from iQue, but the Taiwan Chinese font is still garbled like that.

I don’t think there’s much you can really do about it though, maybe if you install the font used by JAP, USA, or EUR but that might break text from displaying in other apps. The font loading in CTRPF just needs some work.

**Comment by siemanzzz** [comment]
> 是的，这是导致这种情况的另一种情况。前段时间iQue的中文字体已经修复了，但是台湾的中文字体还是这样乱码。
> 
> 我不认为你能真正做些什么，也许如果你安装了日本、美国或欧元使用的字体，但这可能会破坏文本在其他应用程序中的显示。CTRPF 中的字体加载只需要一些工作。
My situation is a bit unique. Chinese 3ds users are using 3ds from other countries then use third party Chinese localization system and software, my 3ds is Japanese version, so the language of the plugin can change to Japanese after I use the font tool, but I can't read it :(

**Comment by FoofooTheGuy** [comment]
So you previously had the Japanese font but changed it to the font for Chinese?
Did you only change the font or did you change the region with a CTR transfer image?

**Comment by siemanzzz** [comment]
Yes, I changed the language to Chinese when I cracked it, as well as when I used the plugin I used ACG SharedFontTool to change the system font to display the plugin properly

**Comment by siemanzzz** [comment]
The 3DS is still essentially a Japanese version of the machine, just in a different language

**Comment by siemanzzz** [comment]
> So you previously had the Japanese font but changed it to the font for Chinese? Did you only change the font or did you change the region with a CTR transfer image?

Thank you so much for always answering my questions and Merry Christmas!

**Comment by NeitherHateNorLike** [comment]
不知道现在的你还是否需要这个帮助，我找到了字体模糊的解决方法。
1.关机后长按“select”打开3ds，进入luma设置菜单栏，选择“boot chainloader”，之后选择“Chinese_system_installer”进入3ds系统中文汉化补丁菜单。
2.打开系统汉化补丁后，会弹出备份nand的选项，如果有需要可以备份一下，没需要就跳过。
3.进入汉化补丁菜单后，按照我写的顺序选择“（3）other function：其他功能”→“（4）fonts change：改变字库”→"ActionReplay C" /“offical  C：官方神游国航字库"
4.切换字库之后重做一的第6步打开动森新叶，插件菜单文字就能正常显示了。
这个方法本质是改变字库，只要改成插件支持的字库就能正常显示插件菜单的文字。
