### ISSUE TITLE
Item Commands were removed

### ISSUE THREAD

**Issue by CharjabugMista** [RedShyGuy/Vapecord-ACNL-Plugin#15]
The commands menu in inventory codes, like clear inventory, are missing. They were very useful, I don’t know why you would remove them.

**Comment by CharjabugMista** [comment]
nevermind

**Comment by CharjabugMista** [comment]
nevermind, found clear inventory in the quick menu

**Comment by RedShyGuy** [comment]
The codes were in the plugin twice, once in the commands and once in the quick menu. So I decided to remove the commands so the code isnt duplicated inside the plugin anymore🙂
