### ISSUE TITLE
Assorted Issue

### ISSUE THREAD

**Issue by FayeReagan** [RedShyGuy/Vapecord-ACNL-Plugin#157]
Random Sizing at Encyclopedia is too big

Catalogs filled with some "???" items

**Comment by DrxyYT** [comment]
Those are items you aren't supposed to have because I have them too.

The Encyclopedia is filled with random sizes if you use the "Fill Encyclopedia" code. @FayeReagan

**Comment by FayeReagan** [comment]
I got your point.
I mean for "Random Sizing" issue, it is technically fixable by limiting the "Random" value and as for "???" in catalogs, i haven't look at the code yet so i have no idea if it is fixable by not "enabling" it on its address/memory

**Comment by RedShyGuy** [comment]
I don't see an issue with the random sizes being too big
And as for the items with ???, that is also not an issue.
It unlocks EVERY item in the catalog, even unobtainable ones.

**Comment by FayeReagan** [comment]
Got it.
My mistake, i thought you were also aiming for more "realistic" approach with this plugin like correct catchable sizing and clean catalog without "???" Items.
I'll close this unnecessary issue
