### ISSUE TITLE
enhancement idea: decorating your town with regular furniture

### ISSUE THREAD

**Issue by yumizzuko** [RedShyGuy/Vapecord-ACNL-Plugin#158]
i was just thinking of this, and if it is possible, but maybe it would be great to add an option to decorate your town with regular objects/furniture (such as the bike, the small streetlamps, etc) just like in acnh! im in no way an expert in coding so i dont know if it would be possible but im still leaving the idea here :DD

**Comment by RedShyGuy** [comment]
That is an extremely difficult and time consuming process. It would need the game to be open source or something to add that much new content. This plugin won't focus on it
