### ISSUE TITLE
Hidden Drawable::operator() Causes Build Error in TouchKey.hpp

### ISSUE THREAD

**Issue by Billyfury** [RedShyGuy/Vapecord-ACNL-Plugin#160]
Hey, when I try to build the library, I get this error: `virtual bool CTRPluginFramework::Drawable::operator()()' was hidden`  in the following file: `libctrpf/include/CTRPluginFrameworkImpl/Graphics/TouchKey.hpp`.
I fixed this error by adding the following line at the end of the `TouchKey.hpp` file:
```cpp 
using Drawable::operator();
```
I'm not an experienced programmer, idk if my line is very useful. So please, if it’s useless, let me know.
I didn’t create a fork because it’s just a simple line addition

**Comment by FoofooTheGuy** [comment]
Where exactly in TouchKey.hpp did you add that line?

**Comment by Billyfury** [comment]
At the end of the TouchKey class, just after all the booleans

**Comment by FoofooTheGuy** [comment]
Thanks, this was an error caused by a warning and since libctrpf is compiled with `-Werror`, it treats every warning as an error
