### ISSUE TITLE
Crashes encountered at any time (online, offline, idle, moving, etc.) [v1.8.1]

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#18]
Hello. I have been encountering crashes while away from my game and online.

This narrows the problem down to any cheat that is doing something while
the player is idle, right?

Image:
![image](https://user-images.githubusercontent.com/69535694/98765669-4722be00-23a4-11eb-8ce9-22c27f8540dc.png)

------
>Game: ACNL 1.5
>Region: USA
>Plugin Version: 1.8.1
------

Many thanks if you choose to fix this. If not, I'll deal with the errors I guess. Oof.

**Comment by RedShyGuy** [comment]
Hm that is weird. There is of course alot of background stuff happening in the background of the plugin you don't see. I try to see if I crash too if I just Idle there. Do you have any cheats enabled?

**Comment by SirEnder125** [comment]
Yes, I have cheats enabled.

The following:
-----
>Pickup Seeder,
>Fast Text,
>Keyboard Extender,
>Room Warp,
>3 Numbers on Island,
>Move Furniture,
>Text to Item,
>Chat Text2Item,
>Quick Menu,
>Probably more...
-----

Well, that's about all I have enabled.
Thanks for trying to fix.

**Comment by RedShyGuy** [comment]
Okay thanks. Does it only crash on the island? And if so only online island?

**Comment by SirEnder125** [comment]
I have only seen these crashes while online, while my town gate is open and visitors are there or when I visit someone.
Also at island. Obviously.

**Comment by RedShyGuy** [comment]
Alright thanks for these infos!! I will test it out and see why it happens!

**Comment by SirEnder125** [comment]
Ok, thanks! 👍🏻

**Comment by RedShyGuy** [comment]
I apologize but I just couldn't reproduce your issue. It just never crashed for me😐.
Are you playing US 1.5?

**Comment by SirEnder125** [comment]
Yes, I am... Maybe if you try using my CTRPFData.bin, it would enable all my cheats for your game, right?
Maybe there's a cheat I didn't mention.

**Comment by RedShyGuy** [comment]
If you want to you can send it to me yes. Its worth a try👍

**Comment by SirEnder125** [comment]
Ok, I will get it.

**Comment by SirEnder125** [comment]
[CTRPFData.zip](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/files/5527092/CTRPFData.zip)
Here it is.

**Comment by SirEnder125** [comment]
EDIT TO MY ERROR REPORT:
My game just crashed while using best friend chat, in town.

It is not an online-only bug.

**Comment by RedShyGuy** [comment]
Could you try playing with no cheats active while the plugin is running to see if it still crashes? I still cant encounter any crashes myself and that info would narrow down the problem by quite alot!🙂

**Comment by SirEnder125** [comment]
Ok, I'll try.

**Comment by SirEnder125** [comment]
By the way, an error log would be nice for this plugin.
Writing the name of a cheat that caused the error to text a file?

That may help find the issue.

**Comment by RedShyGuy** [comment]
That wouldnt be possible. Maybe the dev of CTRPF could implement something like this but i cant.

**Comment by SirEnder125** [comment]
Oh, nothing that could write the name of the current function or something?

**Comment by RedShyGuy** [comment]
No not really

**Comment by SirEnder125** [comment]
Ok. Well, I hope you can find what is causing the issue.

**Comment by SirEnder125** [comment]
I think the cheat causing the issue is "Walk Over Things".
It only causes errors after actually being used, though.

**Comment by SirEnder125** [comment]
Ok, I only had Walk Over Things turned on and an error occurred.

**Comment by RedShyGuy** [comment]
@SirEnder125 one question, did you encounter these random crashes on the newest release yet?

**Comment by SirEnder125** [comment]
No, not yet. It seems to be working fine! 👍🏻

**Comment by SirEnder125** [comment]
Can you please tell me how your plugin is CTRPF 0.6.0 if the
latest release of CTRPF is 0.5.1??

**Comment by RedShyGuy** [comment]
The latest is 0.6.0. Tho my plugin uses an Alpha Version of 0.6.0 which isn't public.

**Comment by SirEnder125** [comment]
Will it be public or is it private forever?

**Comment by RedShyGuy** [comment]
It will be public when it is ready for a release.
