### ISSUE TITLE
“Outdated plugin file”

### ISSUE THREAD

**Issue by PianoHarmony** [RedShyGuy/Vapecord-ACNL-Plugin#19]
Hi! So I’m running a New Nintendo 3DS and I’ve run into a bit of a problem with this plugin. I have tried both methods of installation, manual and direct, but whichever way I do, whenever I open the game, I get an error message. There should be a picture attached but the error reads:

“Outdated plugin file
Check for an updated plugin
Error code: 0xD8E07402”

Does anyone know what this means or how to fix it?

Picture:
![image](https://user-images.githubusercontent.com/75461925/101116816-75627a80-35ab-11eb-90b6-9be103c92f69.jpg)

**Comment by SirEnder125** [comment]
You are most likely using an outdated Luma3ds version.
Try Luma v10.2.1

**Comment by PianoHarmony** [comment]
> You are most likely using an outdated Luma3ds version.
> Try Luma v10.2.1

I just checked, that’s the version I’m currently running

**Comment by SirEnder125** [comment]
Well, I have seen this before, that usually fixes it...
I personally have not tried this version yet because my ds is not updating so I can't do much.
This is 1.8.2, correct?

**Comment by PianoHarmony** [comment]
> Well, I have seen this before, that usually fixes it...
> I personally have not tried this version yet because my ds is not updating so I can't do much.
> This is 1.8.2, correct?

Yep, that’s the one

**Comment by SirEnder125** [comment]
I will try downloading it.

**Comment by SirEnder125** [comment]
I do not get that error... I do get an arm11 exception.

**Comment by PianoHarmony** [comment]
> I do not get that error... I do get an arm11 exception.

I haven’t gotten any exception errors along the way, but I’ve tried different variations of Luma and none of them seem to be any different

**Comment by SirEnder125** [comment]
Has anyone been able to use this plugin successfully?

**Comment by RedShyGuy** [comment]
You need to use the boot.firm from the zip. It does work fine

**Comment by RedShyGuy** [comment]
Not sure what you did wrong🤔

**Comment by RedShyGuy** [comment]
You could try reinstalling the plugin

**Comment by RedShyGuy** [comment]
Okay sorry I am now more awake to actually help. @PianoHarmony you probably already had a previous plugin before Vapecord, hence the outdated plugin error. Try to locate the old files in your plugin directory (all the `.3gx` files which are not named `Vapecord_Public`) and delete them, the plugin should work then. Now to @SirEnder125 , you should first as said try reinstalling the plugin to see if that helps!

**Comment by RedShyGuy** [comment]
> Has anyone been able to use this plugin 
Yes everyone one my Discord Server who already tried it didn't have any problems using it. I even asked the dev of Universal Updater to download the plugin through it which also worked just fine!

**Comment by SirEnder125** [comment]
My game works fine now,  I was using 10.2.1 and it failed... the version from Vapecord.Public.zip works fine.

**Comment by PianoHarmony** [comment]
> Okay sorry I am now more awake to actually help. @PianoHarmony you probably already had a previous plugin before Vapecord, hence the outdated plugin error. Try to locate the old files in your plugin directory (all the `.3gx` files which are not named `Vapecord_Public`) and delete them, the plugin should work then. Now to @SirEnder125 , you should first as said try reinstalling the plugin to see if that helps!

It turns out I had another plugin from someone else installed. I deleted it and it works fine now as far as I’m aware. Thank you so much!

**Comment by RedShyGuy** [comment]
Glad it works for you now!🙂
