### ISSUE TITLE
Cheat Help Thread

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#20]
I have ONE question, please answer, then I'll keep my issues on topic, I promise!!!!!!!!!!!!!!
I have recently started making my own plugin (Not near as good as yours) and I have no idea
how I can find addresses at which to edit. I am trying to make a money cheat that gives the
player 999,000,000 bells. What can I do to find the address that holds this data at which to
write the value 999000000? Very sorry for being off-topic, but where else can I ask (do not direct
me to gbatemp, please.) I don't have an account and do not plan on getting one. Sorry!

**Comment by RedShyGuy** [comment]
Don't worry you are good! If you have any questions unrelated to the plugin you can always DM me on Discord. My tag is Lukas#4444 
I can help you there more about any new leaf cheats related problem.
But about the money: new leaf encrypts the money so you can't find it as easily. If you try to search for the actual value of the money amount you won't find anything useful. The best way to find it would probably be to do an unknown search in CTRPF and search for **Not Equal To** everytime you change the money amount.

**Comment by SirEnder125** [comment]
Welp, gee, I don't have Discord, and I'm not sure I'm allowed to get it.
But this search you mentioned, where can I do a search such as this?
Also, is ACNL-NTR-Plugin Open Source to allow others to use it's code?
(In other words, can I use his code in my plugin? Crediting him, of course.

**Comment by RedShyGuy** [comment]
In CTRPF on the bottom screen is a Search Button. Also ACNL Multi is open source and you can use the codes out of it, tho as per license you need to publish your Source Code, the dev of that plugin specifically said that to me months ago.

**Comment by SirEnder125** [comment]
Ok, I'll publish my source code once I publish my plugin, if that's what I am supposed to do.

I tried a search of type Not Equal To and the value (hex) 999000000 and I got a
lot of random addresses, I don't know what to do..

**Comment by SirEnder125** [comment]
Nevermind, I can't figure out how to make a plugin... :/

**Comment by SirEnder125** [comment]
search number 102 and still 1325 hits... Is this normal?

**Comment by RedShyGuy** [comment]
The game has lot of data, so yes that is normal.

**Comment by SirEnder125** [comment]
Ok. Thanks. I accidentally hit reset so I got to start again some time.
I don't even know how I would make a cheat with that since it is encrypted..
Would I have to encrypt the data before writing it?

**Comment by RedShyGuy** [comment]
Yep! Slattz documented the function to encrypt it: https://github.com/Slattz/ACNL_Research/blob/0fb6857f0aa2a3e8a2031110c92400aa5fd85ba9/010%20Templates/garden_plus.dat.bt#L60

**Comment by SirEnder125** [comment]
Oh, am I allowed to use that?

**Comment by RedShyGuy** [comment]
The encrypter/decrypter functions are directly out of the game, found them myself too some time ago. So yes you can freely use them.

**Comment by SirEnder125** [comment]
Oh, ok. Thanks. :) Tell me, were you able to narrow the amount of addresses down to 1
when searching for the money address?

**Comment by RedShyGuy** [comment]
Not quite, but it narrowed down the content inside the garden_plus to 1. So kinda yes! The other results are not stuff that is located in the garden_plus.

**Comment by SirEnder125** [comment]
I'm not quite sure what you mean, you searched the file garden_plus.dat or you found the address using
"Search"? How can you tell which addresses are from garden_plus.dat?

**Comment by RedShyGuy** [comment]
Depends which game region you use, which one do you use? I can tell the garden plus position then for you

**Comment by SirEnder125** [comment]
I use the USA version.
Are you saying that I will be editing the actual savegame file?

**Comment by SirEnder125** [comment]
Sorry, what are you going to do?

**Comment by RedShyGuy** [comment]
The US GardenPlus starts at the address `31F26F80` and ends at `31FB0A80`.
And no you can still write values to that address as with every other one.
The Game loads in the save file into the memory, thats why it is present there.

**Comment by SirEnder125** [comment]
Oh, that's way less complicated than I thought. Lol, thanks! :D

**Comment by SirEnder125** [comment]
I'll try to find the address now.

**Comment by RedShyGuy** [comment]
Good luck!

**Comment by SirEnder125** [comment]
Thanks. 😃

**Comment by SirEnder125** [comment]
I found two addresses that start with
> 31F
Is it one of these by any chance?

**Comment by SirEnder125** [comment]
Oh, by the way, I did not specify, I am searching for the wallet value,
not the ABD address.

**Comment by RedShyGuy** [comment]
> I found two addresses that start with
> 
> > 0x31F
> 
> Is it one of these by any chance?

It is both to be exact! The encrypted money value is a 64Bit value, so it is 16 numbers long.

**Comment by SirEnder125** [comment]
Ok, I'll use the encryption function you gave me a link to and
use Process::Write64()? I don't even know how to do it...

**Comment by RedShyGuy** [comment]
Well the encrypter returns the 64bit money value, you can then write that to the bank address through Write64 yes.

**Comment by SirEnder125** [comment]
Ok, well, the encrypt function only takes one parameter, how do I use both addresses?
> addressX + addressY?

**Comment by RedShyGuy** [comment]
Yes the encrypter just uses the decimal input. Like input the value of the money you want.

And about the write stuff
For example 
1st address = 31F2DF28
2nd address = 31F2DF2C

To write a 64bit value to it you would do it like this:
Process::Write64(0x31F2DF28, value);

**Comment by SirEnder125** [comment]
Oh, yeah. It will write the value, CTRPF just writes it at 32bit, correct?
Well, thanks.

**Comment by RedShyGuy** [comment]
What? If you use Write64 it will write 64bit

**Comment by SirEnder125** [comment]
I know, I just got confused about the 2 addresses, I know now.

**Comment by SirEnder125** [comment]
I get this compile-time error:
> Random: Undefined identifier

What file do I include?

**Comment by SirEnder125** [comment]
Hey is the ABD amount of money going to be
a bigger amount of addresses?

**Comment by RedShyGuy** [comment]
You need to use the ctrpf included function for random, it is Utils::Random(start, end);

**Comment by SirEnder125** [comment]
Ok, I now have 2 cheats:
1. Bank Editor
2. Wallet Editor

I was thinking about making a name editor...
How many bytes is it? I don't see how I would do it correctly...

**Comment by RedShyGuy** [comment]
Great job so far!
Text strings are stored in hex inside the code. You can simply convert text to hex with a converter like this: https://www.browserling.com/tools/text-to-hex

Then just search for the hex, but info: the player name is stored as UTF16. Which means one letter has 16bits. So for example the letter A is 41. In UTF16 it would be 0041.

**Comment by SirEnder125** [comment]
Ok, thanks. I'll test it out, though, how do I enter the whole name at once?
If that is even necessary... I don't know.

**Comment by RedShyGuy** [comment]
You can only enter 2 letters at once, as 2 letters are 32bit total

**Comment by SirEnder125** [comment]
Oh, ok, well so I do the whole name 2 letters at a time or just one search of two letters?

**Comment by RedShyGuy** [comment]
One search of two letters

**Comment by SirEnder125** [comment]
Ok, I search 0041006C and got 2 hits, edited each and nothing changed...

**Comment by SirEnder125** [comment]
Also, I entered 0041006C and it changed it to 41006C.
Does this do anything that will prevent me from finding
the address? (I wouldn't think so...)

**Comment by SirEnder125** [comment]
I figured out how to change my name.

**Comment by RedShyGuy** [comment]
WriteString

**Comment by SirEnder125** [comment]
Oh, gosh... I can't believe I didn't think of that. Lol

**Comment by SirEnder125** [comment]
Thanks, I think I got the name changer working, maybe I'll release it sometime around
Christmas.
One thing, I was thinking of making a TPC message backup/restore hack, though, I know
nothing about reading from files on 3ds. On Windows I would just use std::ifstream, but it
does not seem to work. I don't know much about CTRPluginFramework::File class, but I need
a function like std::getline(std::ifstream, std::string) that works on 3ds. Any ideas how I can do
this?

**Comment by RedShyGuy** [comment]
You can check out my ACHHD Source Code. You can use anything you want out of it if you want to! Here a code which uses a dump/restore system: https://github.com/RedShyGuy/Vapecord-ACHHD-Plugin/blob/master/Sources/Folders/SaveCodes.cpp

**Comment by RedShyGuy** [comment]
Beware that some stuff in it is poorly written 😅. I don't work on it a lot so I rarely write stuff better.

**Comment by SirEnder125** [comment]
Ok, thanks. I'll be sure to try it. :)
> Beware that some stuff in it is poorly written 😅.

I believe that I tried to compile it once before I knew
anything about how to make CTRPF plugins, I got like
200 errors. I guess I forgot to download a file or something.

**Comment by SirEnder125** [comment]
Thanks! I can really use the stuff in that source, though, I do need a way
to read a file line by line, like how std::getline() does it.

**Comment by RedShyGuy** [comment]
You would need to read the file, with:
```cpp
/**
* \brief Read file
* \param buffer Where to read the data to, ensure the buffer is large enough
* \param length Size to read in bytes
* \return
* Either a value in \ref OPResult or an error code from FS service
*/
int     Read(void *buffer, u32 length) const;
```
There isn't something like `getline()` sadly, this is the only way to actually read a file.

**Comment by SirEnder125** [comment]
Oh, ok. Thanks, I'll try it.

**Comment by SirEnder125** [comment]
Ok, I think my plugin is going well so far. I do want to add "Walk Over Things", though.
I do not know how. It looks like some kind of a patch. I know nothing about patches.
Is "Walk Over Things" an easy cheat to make, or no?

**Comment by RedShyGuy** [comment]
Its more difficult than easy save edits.
The Walk Over Things cheat we use is an ASM Patch, much more stable and better than non ASM stuff. To make such a cheat you likely first need the non ASM version. The collision offset is near the coordinates of the player. If you do find it you would need to debug it through IDA for example. Then you could find where the game handles the collisions and then disable them. 
But you can really just use Ryans version. You are allowed to take cheats out of it, just not actual code if you understand what I mean.

**Comment by SirEnder125** [comment]
Ok, uh, what is IDA?

**Comment by RedShyGuy** [comment]
https://www.hex-rays.com/products/ida/

I use it to create cheats for my plugin. You can't really create much stuff without a debugger.

**Comment by SirEnder125** [comment]
Oh, ok. Is it free? By the way, I know that ASM is some kind of language but
I don't know it. Do I need to know it?

**Comment by RedShyGuy** [comment]
IDA with all extensions and all costs 20k $ (not joking). But you can of course get it through, well other methods I won't discuss.
And ASM is assembly, you actually don't need to know much of it. Just some basics to get through.

**Comment by SirEnder125** [comment]
Ok, well I don't know much about debugging 3ds stuff and I doubt that I can use IDA. Lol
I don't think that I can even find the player coordinates address... I am not very good at this
I guess. My plugin will have to stay how it is until I can figure out a good way to improve it.
Sadly.

**Comment by RedShyGuy** [comment]
When I started I also didn't know a thing. But if you practice and practice you will slowly understand everything!
And I can always help you if you got any questions!

**Comment by SirEnder125** [comment]
I really don't know what to do now. If I need a debugger I don't really even know
what one is. Or does, for that matter.

**Comment by RedShyGuy** [comment]
It lets you see where the game triggers certain stuff (for example, it can do more than that).
For example you put a watchpoint at the player inventory address. Then change something there. The debugger will register the change on that address and will tell you what function inside the game changed it. Thats how you can find inventory related code.

**Comment by SirEnder125** [comment]
Wow, that's cool. But I definitely don't have $20k to spend on a debugger that I wouldn't even
really know how to use. I'm only 13!!

**Comment by RedShyGuy** [comment]
As said, there are...other ways of doing it. No one I know who uses it..got it the normal way. If you understand what I mean.

**Comment by SirEnder125** [comment]
What, you're saying that they got it free (somehow)?

**Comment by SirEnder125** [comment]
No, I am afraid I do not understand what you mean.

**Comment by SirEnder125** [comment]
What exactly DO you mean?

**Comment by SirEnder125** [comment]
Is there any free debuggers that you know of?

**Comment by RedShyGuy** [comment]
Ghidra has a debugger, tho without any UI

**Comment by SirEnder125** [comment]
UI? You mean it's just a console?
Is it free?

**Comment by RedShyGuy** [comment]
Ghidra is free yes.
And the debugger is afaik just a console ya.

**Comment by SirEnder125** [comment]
Does it work well, though? Like will it work to make the Walk Over Things cheat?

**Comment by RedShyGuy** [comment]
I created a discussion where we can talk further about that stuff. So we aren't in the issues tab anymore!
https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/discussions
