### ISSUE TITLE
Unclear Statement in Description: Take TPC Pic cheat

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#21]
Hello. I am confused about one part of this cheat's description:
> "You can also freeze the screen while in the camera to take screenshots to put on swapdoodle."

What exactly does this mean?
Which camera? Amiibo Camera, or TPC Pic Camera Booth?

If it is the Amiibo camera, that's cool but how does it work and how can I do it?

Thanks.

**Comment by RedShyGuy** [comment]
TPC is short for "Town Pass Card". The TPC has a picture in it of the player. The TPC Cheat lets you freeze the current frame, while it is frozen you can then teleport to the TPC Photo boot where it will take the picture. The frozen frame will be used in that tpc picture.
Hope I explained it good😅

**Comment by RedShyGuy** [comment]
You can go to the Amiibo camera through teleporting to it, its a room. If you go there while the frame is frozen you can then make a picture in the amiibo camera.

**Comment by SirEnder125** [comment]
But what is this thing about swapdoodle?
