### ISSUE TITLE
Vapecord v1.9.0 and v1.9.2 plugin crashes on full European .cia version of ACNL Welcome Amiibo (includes update)

### ISSUE THREAD

**Issue by doctahoo** [RedShyGuy/Vapecord-ACNL-Plugin#28]
Hi, RedShyGuy,

FYI, recently I tried to use your plugin (v1.9.0) with the EU version of ANCL Welcome Amiibo on latest Luma 10.2.1 edition for plugins by Nanquitas and firmware 11.13 EU on my New 2DS XL console, but it crashed every time at the very beginning just upon loading the plugin with the typical black screen with register data in white letters. All I could do was press a button to shut down the console.

This does not happen with your v1.9.0 plugin and ACNL Welcome Amiibo US version, which works flawlessly.

Do you know what can be the reason?

Thanks in advance.

**Comment by RedShyGuy** [comment]
Which ACNL EUR is it? The one with Welcome Amiibo preinstalled or the one with WA as an update? Also check if you use the newest version of ACNL.

**Comment by doctahoo** [comment]
It happened to me with the EUR .cia version of the game. I will try your latest update (1.9.2) to see if your plugin works now. 

It was strange, because there were no issues with the plugin + US .cia version of the game. It only crashed with the EUR .cia version.

**Comment by RedShyGuy** [comment]
The cia might not be correct. Buy the game and try again. It does work for all regions just fine. You might just have a weird cia

**Comment by doctahoo** [comment]
I'm afraid this is not the case. As I commented above, I tried three different .cia files with different hashes just to make sure it was not because of a faulty .cia file.

I have borrowed a retail cartridge copy of the game, but it crashes all the same. So there is definitely an issue with the EUR version of the game. This does not happen with the USA version, which works fine.

I have a EUR New 2DS XL console with firmware 11.13.0-45E and Luma boot.firm for 3gx plugins by Nanquitas.

Your plugin works with USA ACNL Welcome Edition standalone, EUR ACNL + separate update 1.5, and ACNL Welcome Luxury + Update 1.6 with no issues.

The only version that does not work is EUR ACNL Welcome Edition standalone.

**Comment by RedShyGuy** [comment]
Try this plugin, https://github.com/RedShyGuy/ACNL-NTR-Cheats/releases/tag/v4.3
If it works we know its an issue with vapecord. If not we know its an issue with your game

**Comment by RedShyGuy** [comment]
Though I highly doubt it is vapecore. As you are the first person having that issue.

**Comment by RedShyGuy** [comment]
Make sure to also download the update files for EUR WA Preinstalled as that version also received some updates in the past. The plugin only works for the newest version of ACNL

**Comment by doctahoo** [comment]
One question: Do I need to be on the latest Nintendo firmware (11.14.0-46E) for your plugin to work?

**Comment by RedShyGuy** [comment]
I don't think so, I am unsure

**Comment by p4l3tt3** [comment]
The Welcome Amiibo update is version 1.4, but the version this plugin is written for is 1.5, even the cia with the update preinstalled needs an update from 1.4 to 1.5

**Comment by RedShyGuy** [comment]
Yes that is correct.

**Comment by p4l3tt3** [comment]
Also, if you didn't get banned or did something funky to your system, you should just be able to download the 1.5 update for ACNL: WA
