### ISSUE TITLE
Strange custom design glitch

### ISSUE THREAD

**Issue by PianoHarmony** [RedShyGuy/Vapecord-ACNL-Plugin#35]
Hi, I’m back again, sorry! I just updated to the new version last night, and I noticed something weird. I don’t know how circumstantial this is, but my character was wearing shoes, pants, and a custom design shirt. So I just made a custom dress and decided to change her outfit. So like normal, the pants went into the pockets inventory. But then so did the shirt. What’s even weirder was the shirt (custom design) was showing as the furniture leaf thing. I didn’t touch it because I didn’t know if it’ll crash my game or not. I just used the quick menu to clear my inventory. But I just figured I’d bring awareness to this glitch, even if it’s just a small one.

**Comment by PianoHarmony** [comment]
Update, I changed out of the dress and it did the same thing. The dress is showing as furniture in my pockets.

**Comment by RedShyGuy** [comment]
Thats very weird. But thanks a lot for reporting that! I will look into it

**Comment by SirEnder125** [comment]
That's been happening for quite some time, I often tell people that I can give them my designs
to troll them, then I give them a leaf with a name of one of their designs (at least they see it that
way.) and they cannot pick it up. :) Cruel, I know. :smile:

**Comment by RedShyGuy** [comment]
So I looked at it a bit more and it doesn't seem to be anything bad!
The plugin just allows you to put everything into the inventory (like trees), therefore it also lets you get the custom outfits. As they do have an own ID they can be spawned in just fine. And don't worry they don't break or harm anything.🙂
