### ISSUE TITLE
Issue when using plugin on different game

### ISSUE THREAD

**Issue by Name2c** [RedShyGuy/Vapecord-ACNL-Plugin#36]
A bunch of blank folders and cheats appear along with the "Dev Codes" folder. They're cool but have no use outside of New Leaf. How do I remove these?

**Comment by RedShyGuy** [comment]
That was a mistake by me I apologize. I had these added for developer purposes and forgot to remove them. They will be gone in the next version, I am sorry for the inconvinience!
