### ISSUE TITLE
Acnl Vapecord plugin items dissapear 

### ISSUE THREAD

**Issue by Laura051** [RedShyGuy/Vapecord-ACNL-Plugin#37]
First i said Hello i Need help i have   make my town  beautiful whit this plugin  but its one problem the items from my towns  the plugin items are dissapear  not all but some  idk why can u help me ? i have the new version

**Comment by RedShyGuy** [comment]
What items

**Comment by Laura051** [comment]
> Welche Artikel

Trees and all that plants

**Comment by RedShyGuy** [comment]
Did you maybe use Remove All Items? Or Search And Replace? Those items can't just be gone out of nowhere.

**Comment by Laura051** [comment]
No idea I didn't click anywhere on it I just kept pressing text to item and nothing else I saved and exited the game and where I was back there was a lot I can hardly describe it but all the plants and bushes and the bamboo is disappeared I firmly believe that I haven't pressed anything else

**Comment by RedShyGuy** [comment]
Weird.. were the trees and all at cliffsides?

**Comment by Laura051** [comment]
> Weird.. were the trees and all at cliffsides?

Yeah and they are all dissappear i mean all the items

**Comment by RedShyGuy** [comment]
Ich bin auch in deutschland. Und naja, items an den klippen verschwinden immer. Man kann diese nicht immer da lassen, verschwinden nach einem tag

**Comment by Laura051** [comment]
> Ich bin auch in deutschland. Und naja, items an den klippen verschwinden immer. Man kann diese nicht immer da lassen, verschwinden nach einem tag

Achso schade   dann ist das leider so :)

**Comment by RedShyGuy** [comment]
Jap das kannst du. Geh einfach in die Traumstadt und geh dann dumpe den Save bei den Save Options. Dann geh zurück in deine stadt und restore dort den save.
