### ISSUE TITLE
c++ code to read the english.txt offsets?

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#4]
I would like to know how to read a certain offset from a file.

**Comment by RedShyGuy** [comment]
Hm I am not sure what you mean. Can you explain it a bit more?

**Comment by SirEnder125** [comment]
I mean how do you get the plugin to know what text goes where, like "Save codes" name goes to save codes cheats,

**Comment by RedShyGuy** [comment]
I load the text file into the plugin and it reads the stuff before the :: to assign it correctly to the plugin cheat strings.

**Comment by SirEnder125** [comment]
I don't suppose you could tell me how to do that in c/c++? I'm trying to make a plugin...

**Comment by RedShyGuy** [comment]
No

**Comment by Mell825** [comment]
whoa

**Comment by Mell825** [comment]
"no"

**Comment by Mell825** [comment]
just
whoa
