### ISSUE TITLE
Issues in 1.9.2

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#42]
Hello. I found the following issues:
1. Player selector does not let you select any player after the first selection.
2. Hex Editor/Search are disabled. (Did you mean to do this? (Probably))

I think that was it.

**Comment by RedShyGuy** [comment]
I will look at the first issue. And yes the second one was intended. Some people tried getting stuff out of my plugin via the Hex Editor so to prevent that I disabled it

**Comment by SirEnder125** [comment]
Oh, okay. I'll just use my own plugin for hex edit/search.

Thanks.
