### ISSUE TITLE
Luma3DS fork

### ISSUE THREAD

**Issue by p4l3tt3** [RedShyGuy/Vapecord-ACNL-Plugin#45]
Maybe add clarification that you can't load this plugin (or any other plugin) with "stock" Luma3DS, as plugins are (as of writing this) 
only implemented in a fork

**Comment by RedShyGuy** [comment]
Not really needed, the needed luma version is always inside the plugin zip. 
The guide on how to install the plugin specifically says to extract all files and replace files when prompted.

**Comment by p4l3tt3** [comment]
Yeah ok I get that, that's my mistake, I tried only installing the plugin for ACWL, as I have a legit save on the unmodded game
