### ISSUE TITLE
Crash when trying to download through Universal Uplater

### ISSUE THREAD

**Issue by p4l3tt3** [RedShyGuy/Vapecord-ACNL-Plugin#46]
Title pretty much explains it, maybe it happens because it may try to replace boot.firm?

**Comment by p4l3tt3** [comment]
![image](https://user-images.githubusercontent.com/46242177/111920705-bb771780-8a90-11eb-9ee7-8877e0df9e96.png)

**Comment by RedShyGuy** [comment]
Seems to be a Universal-Updater issue. Report the issue on their github, I can't really help with that sorry!
