### ISSUE TITLE
[Feature Request] Auto-Unburrow

### ISSUE THREAD

**Issue by Joly0** [RedShyGuy/Vapecord-ACNL-Plugin#47]
It would be great to have a feature to automatically unburrow fossils and traps and fill the holes afterwards,
like here https://github.com/rydoginator/ACNL-NTR-Cheats

Additionaly, a check if a burrowed item is below a sea or river would be great, otherwise its impossible to auto unburrow certain things (happened to me already)

Afaik, Vapecord doesnt have such feature, would be great to see it happen

**Comment by RedShyGuy** [comment]
Yea I can make something like that!
