### ISSUE TITLE
[Feature Request] Disable Grass Deterioration

### ISSUE THREAD

**Issue by Wynadorn** [RedShyGuy/Vapecord-ACNL-Plugin#49]
Would it be possible to disable grass deterioration all together?

I've read that grass deterioration is based on how much a tile is stepped on per day. 
So currently if you play "too much" in a day you're bound to end up turning your town into a desert.

The fill all grass command has some issues where it grows grass on tiles where I think it's not supposed to, like the ramp leading to the beach.

**Comment by RedShyGuy** [comment]
Well I could make something like that. Though grass detoration doesnt quite work like that. You can check out my post about it: https://www.reddit.com/r/AnimalCrossingNewLeaf/comments/jq1uqi/grass_deterioration_infos/?utm_medium=android_app&utm_source=share

**Comment by Wynadorn** [comment]
Cool, thanks for letting me know!
