### ISSUE TITLE
NPC Codes folder mentioned in English text... but nowhere to be seen in plugin?

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#5]
Is this a code that is going to be implemented to the plugin??
![image](https://user-images.githubusercontent.com/69535694/93028439-a6996300-f5d9-11ea-9365-b83178d70028.png)

By the way, why was Town Name Changer removed? What bugs was it causing?
![image](https://user-images.githubusercontent.com/69535694/93028521-04c64600-f5da-11ea-8de4-e2074d6b59a4.png)

Also, Edit All Patterns now shows a blank pattern while editing, please fix this!

**Comment by RedShyGuy** [comment]
Yes it is a code that will be added soon

And the code didnt fully change the town name and villagers didnt recognize you

And yes thats a known bug and will be fixed

**Comment by SirEnder125** [comment]
Thank you for responding to this issue.
