### ISSUE TITLE
Chat text-to-item bug

### ISSUE THREAD

**Issue by weegeeluigi999** [RedShyGuy/Vapecord-ACNL-Plugin#50]
When I enable the cheat "chat Text-to-item", all i get is broken red flowers even with valid ID that works with the simple "Text to item". I use that cheat by texting and saying the id and then pushing the correct input. Someone know if it have to be fixed or if I'm dumb ?

**Comment by RedShyGuy** [comment]
Dont send the message, simply input it into the chat and press the hotkeys
