### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Joris441** [RedShyGuy/Vapecord-ACNL-Plugin#56]
Hello and what you can remove the bug from the code, delete item, auto drop? This tends to bug me my character or even crash. Thank you good day

**Comment by RedShyGuy** [comment]
What? I don't know what you mean

**Comment by Joris441** [comment]
Hello infate it has buttons that I spread that bug like the delete item, the drop, and when you sing the codes. I don't know if I'm accurate enough. Have a nice day

**Comment by RedShyGuy** [comment]
You are in no way accurate. Please try to be more specific

**Comment by Joris441** [comment]
Hello
