### ISSUE TITLE
Vapecord Is Not Showing Up - Luma Plugin Loader Enabled

### ISSUE THREAD

**Issue by GeekieFreak** [RedShyGuy/Vapecord-ACNL-Plugin#57]
Hello. I extracted the .zip file to the root of my SD card and I have the correct boot.firm files, but whenever I select Plugin Loader in the Luma config. menu, it doesn't say it's loading whenever I open my game. 

What can I do?

**Comment by RedShyGuy** [comment]
So in `luma/plugins/TitleID/` are the plugin files, like in the zip?

**Comment by GeekieFreak** [comment]
Yes.

**Comment by RedShyGuy** [comment]
May you show me how it looks like in your folders?

**Comment by GeekieFreak** [comment]
![vapecord#3](https://user-images.githubusercontent.com/77691568/118745959-4d976400-b825-11eb-84ce-0ed6ca3374f4.png)
![vapecord#2](https://user-images.githubusercontent.com/77691568/118745960-4e2ffa80-b825-11eb-9583-3a0579f2fbaa.png)
![vapecord#1](https://user-images.githubusercontent.com/77691568/118745963-4e2ffa80-b825-11eb-8235-d72c945a76a7.png)

**Comment by RedShyGuy** [comment]
Those files should not be inside `Vapecord.Public` folder. Unzipping files means grtting the files outside of the zip. You put the zip folder itself also inside the sdcard. Put the luma folder outside Vapecord.Public

**Comment by GeekieFreak** [comment]
Ah, okay. That fixed it. Thanks. 

I'll close this now.

**Comment by GeekieFreak** [comment]
Ah, that fixed it. Thank you. 

I'll close this now.
