### ISSUE TITLE
[CODE REQUEST]

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#6]
I would like to request a code from the Foxxy plugin where you stand at the top left corner
of a space you would like to copy and put in X and Y lengths of the area. (I'm sorry if my writing is hard to understand)

**Comment by SirEnder125** [comment]
To clarify, the code copies the area with the perimeter you enter.
I am not asking for the code, but that you add it to the plugin if you have the code.

**Comment by RedShyGuy** [comment]
Maybe i will make and add something similiar
