### ISSUE TITLE
ErrDisp on Island

### ISSUE THREAD

**Issue by RevolveSk** [RedShyGuy/Vapecord-ACNL-Plugin#60]
Hi. Near everyone time I'm going to the Island, idk why but I always manage to get a bug with the ErrDisp and I can't reboot my Old 3DS XL with pressing a button.  I had enough of this so please tell me how to fix it.
Oh and there is the cheat codes I used. And I'm in the latest version.

Other Players can't push you
Walk Over Things
Coordinate Modifier
Touch Warp
Anti Animation
(Sometimes) Player Selector
(Sometimes) Idle
Walking Remover
Auto Item Dropper
Free Kapp'n rides
Chat bubbles don't disappear
Quick Menu
Keyboard Extender
Custom Keyboard Symbols

Thanks by advance

**Comment by RedShyGuy** [comment]
Are you doing something specific before it crashes?

**Comment by RevolveSk** [comment]
I just use hacks when there are people on Island. And idk why but it takes an eternity for someone to join and after it crashes.

**Comment by SirEnder125** [comment]
I've experienced this same effect after using Player Selector.

**Comment by RevolveSk** [comment]
oh me too

**Comment by RedShyGuy** [comment]
The auto switch back of the Player Selector doesn't work perfectly as I can tell. As long as I don't figure out how to make it work better I can't do much about it sorry!

**Comment by RevolveSk** [comment]
Thanks a lot:) I hope Vapecord will be much better in future updates :)
