### ISSUE TITLE
Non-Hacker command items spawn to another person.

### ISSUE THREAD

**Issue by SpongeyBubby** [RedShyGuy/Vapecord-ACNL-Plugin#61]
This may get confusing so I'll try my best to explain here.

I may have found a bug where everytime I do a non -hacker command it has its effects on another person instead of me. For example I try to do n:golden rod expecting it to spawn under me but it goes straight to the other person instead. This also happens to the animation commands when me and my friend were playing the other day, he was trying to do a:1c but it didn't work on him, so I typed it and it took effect on him at last.

Sometimes it goes back to normal but this happens often.

**Comment by RedShyGuy** [comment]
I am aware of these issues and will fix them.

**Comment by FoofooTheGuy** [comment]
This has been fixed and will be in the next release
