### ISSUE TITLE
Items with flags

### ISSUE THREAD

**Issue by cheesysock** [RedShyGuy/Vapecord-ACNL-Plugin#63]
I have been trying to use the non-hacker commands to spawn items with flags (customized furniture). But it always ends up crashing my game, so I am just wondering which flag ID to put, and does it support 2 flags? I'm fine with going to retail to customize the furniture but just wondering

**Comment by RedShyGuy** [comment]
That seems to be a bug, please use the Text2Item cheat for now to get items with flags

**Comment by RedShyGuy** [comment]
Fixed
