### ISSUE TITLE
[CLOSED] Luma says "Plugin outdated" when game boots.

### ISSUE THREAD

**Issue by Ne0nHoriz0n** [RedShyGuy/Vapecord-ACNL-Plugin#64]
I have the correct version of luma and luma 3gx loader, and I also installed vapecord correctly and turned on cheats, but when I boot up the game, it says that it's an outdated plugin.
![WIN_20210622_08_50_18_Pro (2)](https://user-images.githubusercontent.com/84997783/122937055-476e3900-d337-11eb-98a6-a2ee6037b523.jpg)
![WIN_20210622_08_50_48_Pro (2)](https://user-images.githubusercontent.com/84997783/122937058-476e3900-d337-11eb-8494-5948f74b9858.jpg)

**Comment by Ne0nHoriz0n** [comment]
sorry for the bad quality images

**Comment by RedShyGuy** [comment]
Make sure there are no outdated plugin files inside the plugin folders which interfer with Vapecord

**Comment by Ne0nHoriz0n** [comment]
I finally got to looking into it and I found that for some reason, when I tried to replace the plugins folder with an old plugin that didn't work, Windows screwed up and somehow combined the two plugins. My hacks work now
