### ISSUE TITLE
Can't spawn Mannequins 

### ISSUE THREAD

**Issue by kyojn** [RedShyGuy/Vapecord-ACNL-Plugin#66]
I can't spawn Mannequins. The ID doesn't work, nor does the Text2Item. It doesn't pop up, and the plugin says the Title ID is invalid.

**Comment by RedShyGuy** [comment]
Yes, that is intended. Having more mannequins than the game allows will simply break your game completely and will make it unusable

**Comment by kyojn** [comment]
Okay, got it
