### ISSUE TITLE
Town not loading after using hacks

### ISSUE THREAD

**Issue by Ne0nHoriz0n** [RedShyGuy/Vapecord-ACNL-Plugin#67]
After I used the hacks, my town won't load and it will be stuck at the preparing town screen until it crashes. Also, for some reason there are 2 new profiles named N Leaf. How can I fix my town?

**Comment by Ne0nHoriz0n** [comment]
And I know for sure that I installed the plugin correctly this time.

**Comment by Ne0nHoriz0n** [comment]
And it said something about running the process GARDEN_P when it crashed..

**Comment by RedShyGuy** [comment]
Did you maybe mess with your save file?

**Comment by Ne0nHoriz0n** [comment]
Yeah I tried to save the game and them load the save, and then the next day it doesn't load.

**Comment by RedShyGuy** [comment]
I am guessing you somehow broke it, try loading a different save or a backup you made of your town while it still worked
