### ISSUE TITLE
Tan Modifier that works on on other players???

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#7]
My friend wants me to ask if a tan modifier for other people would 
be possible, I understand this would probably be hard to implement
but I just thought I'd ask. Sorry for making multiple issues. I don't know
where else to request codes and such. Sorry if I am annoying.

**Comment by RedShyGuy** [comment]
That probably is impossible, because Tan is not server sided and doesnt really work online

**Comment by Mell825** [comment]
thats SO i

**Comment by Mell825** [comment]
*says nothing to "sorry if i am annoying"*
