### ISSUE TITLE
Town name changer creates new players with the town name?

### ISSUE THREAD

**Issue by 3dshackstimemachine** [RedShyGuy/Vapecord-ACNL-Plugin#72]
Hey, so I was using the plugin and wanted to change my town name, but when I tried to change my town name to "Galaxy", nothing happened. So I rebooted my game to see what happened and 2 new players named "Laxy Gal" have been created. A day later, my town gets corrupted.. Please fix this!

**Comment by RedShyGuy** [comment]
Sounds like you were messing with your Save File before already. You likely partly created those 2 new players yourself at some point but maybe didn't save when creating them so they were kinda bugged

**Comment by Ne0nHoriz0n** [comment]
Yes that happened to me to but I never created any players (intentionally)

**Comment by BioHazard1282** [comment]
This actually corrupted my save ;w;

**Comment by RedShyGuy** [comment]
Town name changer was bugged and works now
