### ISSUE TITLE
Plugin not showign up, plugins are enabled with luma.

### ISSUE THREAD

**Issue by Emilinrose** [RedShyGuy/Vapecord-ACNL-Plugin#77]
I've tried downloading from the universal updater, all the files seem to be in the right place and it looks like it updated the boot file so i'm lost.
![0WbIhDyfSV](https://user-images.githubusercontent.com/13422908/131417916-91fe8ecb-0357-487d-bfdb-bf18e1b97702.png)
![RCfPx833Qk](https://user-images.githubusercontent.com/13422908/131417921-de7dee89-178d-4fe1-b7f5-98edbc99b57b.png)

**Comment by SirEnder125** [comment]
Are you sure about the title id? Is it really ACNL WA USA? A wrong title id could definitely cause the plugin not to boot.

**Comment by Emilinrose** [comment]
The game is US version animal crossing, with the amiibo update. but the cartridge is an original NL game with the amiibo update downloaded. is that the problem?

**Comment by RedShyGuy** [comment]
Yes it is, download the US version of the plugin which is not labeled as "US WA"
