### ISSUE TITLE
quick menu doesn't work

### ISSUE THREAD

**Issue by bkfirmen** [RedShyGuy/Vapecord-ACNL-Plugin#78]
In the latest version of vapecord, the quick menu isn't displayed.

**Comment by RedShyGuy** [comment]
What do you mean with "isn't displayed"?

**Comment by bkfirmen** [comment]
When I press the hotkeys and the cheat is activated, the menu doesn't appear. This also means that it cannot be used.
Sorry if my English is bad or if my bug report is inaccurate. I'm very new at bug-reporting :)
PS: Is there already a German translation of the plugin? If not, I could make a translation.

**Comment by RedShyGuy** [comment]
Do you try to open it when the Plugin Menu is closed? Also did you maybe change the hotkeys of the cheat?

**Comment by RedShyGuy** [comment]
And no there is no germany translation (und ich selber hab keine Zeit dafür leider). You can make one if you want, but to make communication easier I suggest you get Discord as the language files get updated very frequently, and I send the updated ones into a Discord group

**Comment by bkfirmen** [comment]
> Do you try to open it when the Plugin Menu is closed? Also did you maybe change the hotkeys of the cheat?

Yes, I checked the hotkeys, they're all correct. And yes, the menu is closed when I try to open the quick menu.

**Comment by RedShyGuy** [comment]
Try deleting the CTRData.bin inside the plugin folder and try again

**Comment by bkfirmen** [comment]
Thank you, now it works
