### ISSUE TITLE
Chat sender work with luma(I think this is the wrong place to ask, but... I can't seem to find the RIGHT place so I thought I'd ask someone who might know how to make this work) sorry for long title.

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#8]
Hi, you may have seen this:
https://github.com/rydoginator/acnl-chat-sender
I was wondering if you could make it work with
luma other than NTR. If not, fine. Sorry for making
yet another issue... I may be annoying. Sorry.
The chat sender tool sends text from computer into acnl chat.

**Comment by RedShyGuy** [comment]
I did not make that Tool, you can directly ask Rydoginator for that.
