### ISSUE TITLE
I doubt you wanna hear from me again but I found some bugs.

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#9]
Bugs I've found in:
** ------------------------------ **
Vapecord version: 1.8.0
Game: ACNL, USA (Haven't tried acnl:wa yet.)

** ------------------------------ **
Bug 1:
Edit all patterns turns itself off instead of working as the release says it does.
[Note:] When the cheat isn't turning itself off, (or, when it's already off,) it's
making it were you can only delete the patterns you have.

Bug 2:
I don't know what the causing cheat is but the plug crashes quite
often.

Note: I've seen someone at island who's said that they want the old animation
changer menu instead of the new one, (which, overwrites the hotkeys I use for coordinates modifier.)

Thanks.

**Comment by RedShyGuy** [comment]
The first bug is known and already fixed, you can find a fixed version on my discord server, the second i cant help because i dont know which cheats you mean. And the note, you can change the hotkeys of every code just how you want.

**Comment by RedShyGuy** [comment]
I have now edited the 1.8.0 release here on GitHub so it now contains the version with the fixed Edit All Designs!
And don't worry with all your issues, I am glad to hear bugs from Vapecord so I can fix them 👍

**Comment by SirEnder125** [comment]
Ok, thanks. I do not know which cheat causes the crashes I have seen crashes when I'm doing nothing but typing in chat so
maybe it's caused by a cheat that has to do with the keyboard.

**Comment by RedShyGuy** [comment]
Both of these codes work just fine for me in USA🤔

**Comment by SirEnder125** [comment]
I changed the hotkeys to separate them, no errors other than some that happen for no apparent reason.
I don't know the cause. Maybe if you examine your code changes since 1.7.3 and search for bugs, you could fix it?

Thanks.

**Comment by RedShyGuy** [comment]
If you would tell me the exact reason on why it crashes i could fix it fairly fast. But I cant reproduce your issue.

**Comment by SirEnder125** [comment]
Ok, thanks.
