### ISSUE TITLE
Duplication Custom Button only duplicating in same row of inventory.

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#93]
Hey, Lukas. I've noticed while using the duplication custom button, that duplication only works on the same row of the inventory of the item being duplicated. Please note, however, that I have only tried this in the top row of the inventory. It could be, for all I know, that it always duplicates into the first row. 

### Steps to reproduce:
First, enable the duplication custom button. Next, duplicate an item in your pockets until the row in which that item resides is filled, then try duplicating again. When I tried to duplicate again, after the row was full, nothing happened.

### Information regarding versions and whatnot:
**Game version**: ACNL USA v1.5 (White leaf on green background)
**Date**: Eh, about 5 days before the original writing of this issue.

For all I know, you may have already fixed this. Just thought I'd be sure. Sorry if this is a duplicate issue (Pun intended)!!

**Comment by FoofooTheGuy** [comment]
This appears to be fixed when using newer builds of the master.
It will be in the next release
