### ISSUE TITLE
My game consistently crashed throughout gameplay and now I can't play it at all.

### ISSUE THREAD

**Issue by CIRICE04** [RedShyGuy/Vapecord-ACNL-Plugin#95]
![image](https://user-images.githubusercontent.com/97844102/149668567-db540534-4e73-46cc-905f-b4905c87979d.jpeg)

**Comment by RedShyGuy** [comment]
Does it also happen with the plugin disabled?

**Comment by CheesyLouisy** [comment]
yes, but i figured out the cause. I was an idiot and tried to add a third beach ramp. I fixed it with a save editor.
